//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Android.Tools.AndroidSdk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Android.Tools.AndroidSdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while validating the Java SDK installation in &apos;{0}&apos; that was found while searching the paths from &apos;{1}&apos;. Ensure that the Android section of the Visual Studio options has a valid Java SDK directory configured. To use a custom SDK path for a command line build, set the &apos;JavaSdkDirectory&apos; MSBuild property to the custom path. Exception: {2}.
        /// </summary>
        internal static string InvalidJdkDirectory_path_locator_message {
            get {
                return ResourceManager.GetString("InvalidJdkDirectory_path_locator_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while reading configuration file &apos;{0}&apos;. Exception: {1}.
        /// </summary>
        internal static string InvalidMonodroidConfigFile_path_message {
            get {
                return ResourceManager.GetString("InvalidMonodroidConfigFile_path_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while reading the output of &apos;{0} {1}&apos;. Exception: {2}.
        /// </summary>
        internal static string InvalidXmlLibExecJdk_path_args_message {
            get {
                return ResourceManager.GetString("InvalidXmlLibExecJdk_path_args_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Android SDK directory could not be found. Check that the Android SDK Manager in Visual Studio shows a valid installation. To use a custom SDK path for a command line build, set the &apos;AndroidSdkDirectory&apos; MSBuild property to the custom path..
        /// </summary>
        internal static string XA5300_Android_SDK {
            get {
                return ResourceManager.GetString("XA5300_Android_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while retrieving the properties of the selected Java SDK installation. Check that the selected Java SDK installation contains a compatible version of Java and that &apos;java -XshowSettings:properties -version&apos; runs successfully for that installation. Exception: {0}.
        /// </summary>
        internal static string XA5300_AndroidSdk_JdkInfo {
            get {
                return ResourceManager.GetString("XA5300_AndroidSdk_JdkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while finding the Android SDK or Java SDK. Exception: {0}.
        /// </summary>
        internal static string XA5300_AndroidSdk_Refresh_Exception {
            get {
                return ResourceManager.GetString("XA5300_AndroidSdk_Refresh_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Java SDK directory could not be found. Ensure that the Android section of the Visual Studio options has a valid Java SDK directory configured. To use a custom SDK path for a command line build, set the &apos;JavaSdkDirectory&apos; MSBuild property to the custom path..
        /// </summary>
        internal static string XA5300_Java_SDK {
            get {
                return ResourceManager.GetString("XA5300_Java_SDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while validating the .NET for Android installation. Using the Visual Studio installer to repair or reinstall the .NET MAUI component might resolve this problem. Exception: {0}.
        /// </summary>
        internal static string XA5300_MonoDroidSdk_Refresh_Exception {
            get {
                return ResourceManager.GetString("XA5300_MonoDroidSdk_Refresh_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the .NET for Android version..
        /// </summary>
        internal static string XA5300_MonoDroidSdk_XA_Version {
            get {
                return ResourceManager.GetString("XA5300_MonoDroidSdk_XA_Version", resourceCulture);
            }
        }
    }
}
